# Generated by Django 5.1.2 on 2024-10-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.CharField(default='#FF0000', max_length=25),
        ),
    ]
