# Generated by Django 5.1.2 on 2024-10-18 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_habit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habit.category'),
        ),
    ]
