# Generated by Django 5.1.2 on 2024-10-19 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_alter_habit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Hogar', 'Hogar'), ('Escuela', 'Escuela'), ('Trabajo', 'Trabajo'), ('Metas', 'Metas'), ('Otros', 'Otros')], default='Hogar', max_length=100),
        ),
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habits', to='habit.category'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual')], default='Diario', max_length=50),
        ),
    ]
