# Generated by Django 5.1.2 on 2024-10-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0006_alter_category_name_alter_habit_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='description',
        ),
        migrations.AddField(
            model_name='habit',
            name='repetitions',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
