# Generated by Django 5.1.2 on 2024-10-21 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0007_remove_habit_description_habit_repetitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='current_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='last_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
