# Generated by Django 5.1.2 on 2024-10-28 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0009_habitnotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitnotification',
            options={'ordering': ['priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='habitnotification',
            name='frequency_type',
            field=models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='habitnotification',
            name='grouped_habits',
            field=models.ManyToManyField(blank=True, related_name='grouped_notifications', to='habit.habit'),
        ),
        migrations.AddField(
            model_name='habitnotification',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], default=2),
        ),
        migrations.AlterField(
            model_name='habitnotification',
            name='habit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.habit'),
        ),
        migrations.AlterField(
            model_name='habitnotification',
            name='notification_type',
            field=models.CharField(choices=[('initial', 'Inicial'), ('follow_up', 'Seguimiento'), ('urgent', 'Urgente'), ('group', 'Agrupada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='habitnotification',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
