# Generated by Django 5.1.2 on 2024-10-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0009_habitprogress'),
        ('habit', '0010_alter_habitnotification_options_and_more'),
    ]

    operations = [
    ]
